const sb=window.supabase.createClient('https://yceukuehpffktbpengfx.supabase.co','sb_publishable_-8xFlxnjkipxyDihmKphzg_iTveTcqC');
const $=s=>document.querySelector(s);
let schoolsCache=[];
async function show(){let {data:{session}}=await sb.auth.getSession();$('#login').hidden=!!session;$('#admin').hidden=!session;if(session){list();loadRequests()}}
async function list(){let {data,error}=await sb.from('schools').select('*').order('created_at',{ascending:false});if(error){$('#schoolList').innerHTML='<p>Could not load schools. Please sign in again.</p>';return}
schoolsCache=data;
$('#schoolList').innerHTML=data.map(s=>`<article><h2>${s.name}</h2><p>${s.contact_name||'No contact added'} · ${s.form_fields.length} fields</p><p class="linkbox">${location.origin}/teacher.html?school=${encodeURIComponent(s.access_code)}</p><div class="card-actions"><button class="button outline copy" data-code="${s.access_code}">Copy teacher link</button><button class="button outline edit" data-id="${s.id}">Edit</button></div></article>`).join('')||'<p>No schools added yet.</p>';
document.querySelectorAll('.copy').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(`${location.origin}/teacher.html?school=${encodeURIComponent(b.dataset.code)}`);b.textContent='Copied!'});
document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openEdit(b.dataset.id));
}
function openEdit(id){let s=schoolsCache.find(x=>x.id===id);if(!s)return;$('#editId').value=s.id;$('#editName').value=s.name;$('#editContact').value=s.contact_name||'';$('#editAccessCode').value=s.access_code;$('#editMessage').textContent='';$('#editDialog').showModal()}
$('#editForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let id=$('#editId').value;let {error}=await sb.from('schools').update({name:$('#editName').value,contact_name:$('#editContact').value,access_code:$('#editAccessCode').value.trim()}).eq('id',id);if(error){$('#editMessage').textContent='Could not save: '+error.message;return}$('#editDialog').close();list()});
async function loadRequests(){let {data,error}=await sb.from('id_card_requests').select('*, schools(name)').order('created_at',{ascending:false});if(error){$('#requestsList').innerHTML='<p>Could not load requests.</p>';return}
$('#requestsList').innerHTML=data.map(r=>`<article class="request-card"><div class="request-photo" data-path="${r.photo_path||''}">Loading…</div><div class="request-info"><h3>${r.student_name||'Student'}</h3><p>${r.schools?.name||'Unknown school'} · ${r.request_type||''}</p><p class="hint">${r.created_at?new Date(r.created_at).toLocaleString():''}</p>${r.notes?`<p class="hint">Note: ${r.notes}</p>`:''}</div></article>`).join('')||'<p>No requests yet.</p>';
document.querySelectorAll('.request-photo').forEach(async el=>{let path=el.dataset.path;if(!path){el.textContent='No photo';return}let {data:signed}=await sb.storage.from('student-photos').createSignedUrl(path,3600);if(signed?.signedUrl){el.innerHTML=`<img src="${signed.signedUrl}" alt="">`}else{el.textContent='No photo'}})
}
document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))});
$('#sendLogin').onclick=async()=>{let email=$('#email').value;if(!email)return;let {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/admin.html'}});$('#loginMessage').textContent=error?'Could not send the sign-in link.':'Check your email and open the secure sign-in link.'};
$('#addSchool').onclick=async()=>{let names=$('#fieldNames').value.split(',').map(x=>x.trim()).filter(Boolean);let {error}=await sb.from('schools').insert({name:$('#name').value,contact_name:$('#contact').value,access_code:$('#accessCode').value.trim(),form_fields:names.map((label,i)=>({label,type:'text',required:i<3}))});$('#adminMessage').textContent=error?'Could not save: '+error.message:'School saved.';if(!error){['name','contact','accessCode','fieldNames'].forEach(id=>$('#'+id).value='');list()}};
$('#signOut').onclick=async()=>{await sb.auth.signOut();show()};
show();
